-- Day 01: SELECT Basics

-- SQL is not CASE SENSITIVE
-- SQL Query should ends with ";"

SELECT * FROM emp;

1. DDL (DATA DEFINITION LANGUAGE)
	1. CREATE
	2. DROP
	3. ALTER
	4. TRUNCATE
-- New Features
	1. RECYCLEBIN
	2. PURGE
	3. FLASHBACK

2. DML (DATA MANIPULATION LANGUAGE)
	1. INSERT
	2. UPDATE
	3. DELETE

-- New Features
	1. INSERT ALL
	2. MERGE
 
3. DQL (DATA QUERY LANGUAGE) / DRL( DATA RETRIEVAL LANGUAGE)
	- SELECT

4. TCL (TRANSACTION CONTROL LANGUAGE)
	- COMMIT
	- ROLLBACK
	- SAVEPOINT

5. DCL (DATA CONTROL LANGUAGE)  - THIS PART WOULD BE HANDLE BY DATA ADMINSTRATOR
	- GRANT
	- REVOKE



