-- PRACTICE SHEETS
SELECT * FROM DEPT;

ALTER TABLE <TABLE_NAME>
ADD <COLUMN_NAME> [DATATYPES][NEW SIZE];

ALTER TABLE <TABLE_NAME>
DROP COLUMN <COLUMN_NAME>;

ALTER TABLE <TABLE_NAME>
MODIFY <COLUMN_NAME> <NEW_DATATYPE>[NEW SIZE];

ALTER TABLE <TABLE_NAME>
RENAME COLUMN <OLD_COLUMN_NAME> TO <NEW_COLUMN_NAME>;



-- RECYCLEBIN
DESC RECYCLEBIN;
SELECT OBJECT_NAME, ORIGINAL_NAME FROM RECYCLEBIN;


FLASHBACK TABLE <TABLE_NAME> TO BEFORE DROP;

PURGE TABLE <TABLE_NAME>;

PURGE RECYCLEBIN;

DROP TABLE <TABLE_NAME> PURGE;

INSERT INTO <TABLE_NAME>(COL1,COL2,COL3.....)
VALUES(V1,V2,V3..);

UPDATE TABLE  <TABLE_NAME>
SET <COLUMN_NAME> = [VALUE1],
	<COLUMN_NAME> = [VALUE2],
	........................
WHERE <CONDITIONS>;

DELETE FROM <TABLE_NAME> WHERE [CONDITIONS];
